bcgov/range-api

server/config/development.json
server/config/index.js
server/libs/auth.js

Add SSO configuration and remove unused mino config.

Add SSO configuration

---

Jenkinsfile
package.json
server/router/routes/reference.js

Update the reference endpoint to better match recent schema changes.

Fix reference endpoint

---

server/router/index.js
server/router/routes/agreement.js
server/router/routes/client.js
server/router/routes/district.js
server/router/routes/plan.js
server/router/routes/reference.js
server/router/routes/zone.js

Added update, create, and update plan status
Moved authentication middleware to index instead of every endpoint.

Added Plan Endpoint

---

server/router/routes/agreement.js

Add additional information to Agreement and Plan.

Agreement and Plan information

---

server/router/routes/agreement.js

Updated the exclude on Agreement child properties.

Fix agreements exclude

---

server/router/routes/plan.js

Improved the readability of schedule creation.

Tune up schedule creation

---

scripts/ftaimport.js
server/libs/db/index.js
server/libs/db/migrations/2018031003-client.js
server/libs/db/migrations/2018031011-create-agreement.js
server/libs/db/migrations/2018031012-create-client_agreement.js
server/libs/db/models/Client.js
server/router/routes/agreement.js
server/router/routes/reference.js

Work on the Client model / relation and update the script that imports FTA data to include client.

Add client support to data mode.

---

server/libs/db/migrations/2018032801-drop-column-grazing_schedule_entry.js
server/libs/db/models/GrazingScheduleEntry.js

Remove the start_date and end_date columns from the grazing schedule.

Fix schedule dates

---

scripts/ftaimport.js
server/index.js
server/libs/db/index.js
server/libs/db/migrations/2018031003-client.js
server/libs/db/migrations/2018031012-create-client_agreement.js
server/libs/db/models/ClientAgreement.js
server/router/index.js
server/router/routes/agreement.js

I added some pre-processing logic to better format an` Agreement` Client record so that it is better formatted for the clients who use the API.

Improve the format of an agreement clients array

---

package-lock.json
package.json
server/constants.js
server/libs/template.js
server/router/routes/report.js
templates/rup.html

Initial work on populating the RUP template with actual values from the DB.

Initial work on populating RUP template

---

server/constants.js
server/libs/authmware.js
server/libs/db/migrations/2018041801-drop-zone_user.js
server/libs/db/models/User.js
server/libs/db/models/Zone.js
server/router/routes/report.js
server/router/routes/user.js

User roles now come from SSO and are included in the JWT. The API will use them to determine access privileges / restrictions.

Utilize roles in SSO for user access management. 

---

server/libs/authmware.js
server/libs/db/migrations/2018041901-add-column-last_login_at.js
server/libs/db/models/User.js

Make sure that the user has a role provisioned in order to gain access to the system and log when a user last accessed the system.

Improve user authentication

---

server/libs/db/migrations/2018042201-add-column-alt_buziness_name.js
server/libs/db/models/Plan.js

Add alternative business name to Plan

Add alternative business name to Plan

---

server/libs/db/migrations/2018042201-add-column-user_phone.js
server/libs/db/models/User.js

Add field to db and to User model.

Add User phone number field

---

server/libs/db/migrations/2018042201-add-column-alt_buziness_name.js
server/router/routes/agreement.js

Rater than modify the db model for better search ability I just use a RegEx to filter matching zones first then use the results to limit Agreement search.

Improve search criteria of user

---

server/libs/db/migrations/2018042401-alter-column_schedule_year.js
server/libs/db/migrations/2018042402-alter-column_usage_year.js
server/libs/db/models/GrazingSchedule.js
server/libs/db/models/Usage.js

Change the year type from STRING(4) / VARCHAR(4) to SMALLINT so that it can be sorted during a query.

Fix year type

---

Jenkinsfile
server/libs/db/migrations/2018042601-alter-table-user_active.js
server/libs/db/models/User.js

Fix some issues in the db schema.

Fix db schema issues

---

.babelrc
.vscode/launch.json
package-lock.json
package.json
server/libs/db/models/GrazingSchedule.js
server/router/routes/plan.js

Improved the create and update logic for Plan, Pasture, Schedule and Schedule Entry.

Improve plan update mechanics

---

server/router/routes/plan.js

Add PUT endpoint for updating a plan's pasture.

Implement pasture update

---

server/router/routes/user.js

Update the user endpoint to return the current user's profile.

Add user profile

---

server/router/routes/plan.js

If a grazing schedule entry does not exist then create it.

Schedule faux upsert

---

server/libs/db2/index.js
server/router/routes/plan.js

Work on POST call to create a new minister's issue. Below is a sample JSON object that is accepted by the API.
```
{
"detail": "This is a big issue!",
"objective": "Our objective is to address the issue!",
"identified": true,
"issueTypeId": 1,
"pastures": [23, 62]
}
```
@Kyubinhan

Add minister issues

---

server/libs/db2/migrations/20180605104659_delete-minister_issue_pasture.js
server/libs/db2/migrations/20180605104859_delete-minister_issue_action.js
server/router/routes/plan.js

Added the ability to delete minister issues and fixes some issues with the put route.

Add ability to del minister issue
